name: Java CI with Gradle

on:
  push:
    branches:
      - '**'  # This will trigger the workflow on every push to any branch

jobs:
  build:
    runs-on: ubuntu-latest  # You can also use ubuntu-20.04 or ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # This step checks out the code from your repo

      - name: Set up JDK 11
        uses: actions/setup-java@v2  # Set up Java (JDK 11)
        with:
          java-version: '11'  # We're using JDK 11
          distribution: 'adoptopenjdk'  # Use AdoptOpenJDK for compatibility

      - name: Build with Gradle
        run: ./gradlew build  # Builds the project using Gradle (build task)

      - name: Run tests with Gradle
        run: ./gradlew test  # Runs the tests using Gradle (test task)
